apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "45 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: FINANCES_API_URL
                  value: http://finances
                - name: FINANCES_API_ACCOUNT_ID
                  value: "2"
                # - name: FINANCES_API_TOKEN
                #   valueFrom:
                #     secretKeyRef:
                #       name: oidc-token
                #       key: OIDC_M2M_ACCESS_TOKEN
              envFrom:
                - secretRef:
                    name: ts3-scraper-env-from-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ts3-scraper-env
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ts3-scraper-env-from-vault
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: ts3-scraper
