apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "30 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: FINANCES_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: oidc-token
                      key: OIDC_M2M_ACCESS_TOKEN
              envFrom:
                - secretRef:
                    name: ts3-scraper
